name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      config: 'Release'
      
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.102    
      
      # restore dependencies  
    - name: Install dependencies
      run: dotnet restore ./src/Digitalis.sln
      
      # build project
    - name: Build
      run: dotnet build ./src/Digitalis.sln --configuration $config --no-restore
      
      # run tests with built project
    - name: Test PR      
      run: dotnet test ./src/Digitalis.sln --no-restore --no-build --configuration $config
